### ISSUE TITLE
improve the json handling for extra keys already there

### ISSUE THREAD

**Issue by obar1Merger** [obar1/0to100#101]
- [x] improve refresh_)metadata  to keep extra new dict keys

```
python .\main_sb.py refresh_metadata https://learning.oreilly.com/library/view/learn-enough-python/9780138051143
```

should keep  other keys already in jhson and not only the ones calculated

**Comment by obar1** [comment]
- [ ] drop at all refresh_metadata as done autmatically
- [ ] add __repr__
