### ISSUE TITLE
add new sort as last opened

### ISSUE THREAD

**Issue by obar1pr** [obar1/0to100#114]
- [x] I want to be able to order the tocs so I can see the last opened at the bottom ... easier to jump around topics
- [x] add that settign to the yaml

**Comment by obar1pr** [comment]
- [ ] maybe add title too 
not nice
![image](https://github.com/user-attachments/assets/86e18b60-6d7b-40aa-ac1a-e9e4851c91cc)

**Comment by obar1** [comment]
> * [ ]  maybe add title too
>   not nice
>   ![image](https://private-user-images.githubusercontent.com/19518903/355571458-86e18b60-6d7b-40aa-ac1a-e9e4851c91cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjg0NzcsIm5iZiI6MTcyNDEyODE3NywicGF0aCI6Ii8xOTUxODkwMy8zNTU1NzE0NTgtODZlMThiNjAtNmQ3Yi00MGFhLWFjMWEtZTllNDg1MWM5MWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA0MjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNzU5NjIyZGM0MGFmNDliNTAwNmIxNmY0YjdiNzVlYzg1ODc4ZjMzY2QzYjQ4MDM4MWVhNDVmZGFkOWViYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMXNSQZVH9NXXSVPvM46FB7R1sKqtI7-f7xTqs4S-Cw)

maybe another pr
