### ISSUE TITLE
improve toc mr emotis rendering

### ISSUE THREAD

**Issue by obar1Merger** [obar1/0to100#83]
for some reason it renders like that
![image](https://github.com/obar1/0to100/assets/52974043/4a4e705c-d5f4-403d-a9c4-6f8f0f2e5b49)

change adding a table md :P

**Comment by obar1** [comment]
in codeapce looks good

![image](https://github.com/obar1/0to100/assets/387386/d3eb6ab3-46d9-4066-8e14-d46df571c2cd)
